|Alunos                |Matrícula  |
|----------------------|-----------|
|Caio Bertoldo         |2215080050 |
|Danilo Jorge          |2215080007 |
|Diogo Gomes           |2215080033 |
|Guilherme Montenegro  |2215080011 |
|Leonardo Abinader     |2215080042 |

In [112]:
import numpy as np
from prettytable import PrettyTable, TableStyle

In [113]:
# Verificando qual .txt usar
n = (0 + 7 + 3 + 1 + 2) % 4
n

1

### Verificando os dados

In [114]:
dados = np.fromfile('rna-2025.1-pp2.1-dados/data1.txt')
dados

array([ 0.13658687, -0.16460088,  0.        , ...,  0.99252852,
        1.06937678,  1.        ])

In [115]:
m = dados.size//3
dados = dados.reshape((m,1,3))
print(dados.shape)
print(dados.dtype)

(600, 1, 3)
float64


In [116]:
dados

array([[[ 0.13658687, -0.16460088,  0.        ]],

       [[-0.0228559 , -0.01094684,  0.        ]],

       [[-0.02654897,  0.00582183,  0.        ]],

       ...,

       [[ 0.99007304,  0.8921047 ,  1.        ]],

       [[ 0.91691441,  1.15684083,  1.        ]],

       [[ 0.99252852,  1.06937678,  1.        ]]])

In [117]:
X = np.array([[linha[0][0], linha[0][1]] for linha in dados])
y = np.array([[linha[0][2]] for linha in dados]).ravel()

In [118]:
X

array([[ 0.13658687, -0.16460088],
       [-0.0228559 , -0.01094684],
       [-0.02654897,  0.00582183],
       ...,
       [ 0.99007304,  0.8921047 ],
       [ 0.91691441,  1.15684083],
       [ 0.99252852,  1.06937678]])

In [119]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

### Perceptron

In [120]:
class Perceptron:
    def __init__(self, learning_rate=0.1, epochs=100, weights=None):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = weights
        self.bias = None
        self.necessary_epochs = None
        self.total_adjust = 0
    
    def step(self, x):
        return 1 if x >= 0 else 0

    def check_error(self, y_predicted, y):
        return  y_predicted != y

    def fit(self, X, y):
        if self.weights is None:
            self.weights = np.random.uniform(low=-0.5, high=0.5, size=2)
        self.bias = 0
        self.necessary_epochs = 0
        

        for _ in range(self.epochs):
            self.necessary_epochs +=1
            error_counter = 0
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.step(linear_output)
                if(self.check_error(y_predicted, y[idx])):
                    
                    update = self.learning_rate * (y[idx] - y_predicted)
                    self.weights += update * x_i
                    self.bias += update
                    error_counter +=1
                    self.total_adjust+=1
                else:
                    pass
            if error_counter == 0:
                return

    def predict(self, X):
        return np.array([self.step(np.dot(X[i], self.weights) + self.bias) for i in range(X.shape[0])])


### Testes

In [121]:
# eta e intervalos
eta1 = 0.4
eta2 = 0.1
eta3 = 0.01
i1 = [-0.5, 0.5]
i2 = [-100, 100]

In [122]:
# Função para realizar as 10 execuções com as 6 configurações
def test(eta, i):
    min_epochs = float('inf')
    list_total_adjust = []

    for _ in range(10):
        perceptron = Perceptron(learning_rate=eta, weights=np.random.uniform(low=i[0], high=i[1], size=2))
        perceptron.fit(X, y)
        list_total_adjust.append(perceptron.total_adjust)
        min_epochs = min(min_epochs, perceptron.necessary_epochs)

    mean = np.mean(list_total_adjust) 
    std = np.std(list_total_adjust)

    return min_epochs, mean, std

In [123]:
# eta = 0.4 e intervalo [-0.5, 0.5]
min_epochs1, mean1, std1 = test(eta1, i1)
print(f"Mínimo de épocas necessárias: {min_epochs1}")
print(f"Média do total de ajustes: {mean1}")
print(f"Desvio padrão do total de ajustes: {std1}")

Mínimo de épocas necessárias: 2
Média do total de ajustes: 33.8
Desvio padrão do total de ajustes: 14.668333238647124


In [124]:
# eta = 0.4 e intervalo [-100, 100]
min_epochs2, mean2, std2 = test(eta1, i2)
print(f"Mínimo de épocas necessárias: {min_epochs2}")
print(f"Média do total de ajustes: {mean2}")
print(f"Desvio padrão do total de ajustes: {std2}")

Mínimo de épocas necessárias: 9
Média do total de ajustes: 284.9
Desvio padrão do total de ajustes: 148.25144181423667


In [125]:
# eta = 0.1 e intervalo [-0.5, 0.5]
min_epochs3, mean3, std3 = test(eta2, i1)
print(f"Mínimo de épocas necessárias: {min_epochs3}")
print(f"Média do total de ajustes: {mean3}")
print(f"Desvio padrão do total de ajustes: {std3}")

Mínimo de épocas necessárias: 9
Média do total de ajustes: 33.4
Desvio padrão do total de ajustes: 8.42852300228219


In [126]:
# eta = 0.1 e intervalo [-100, 100]
min_epochs4, mean4, std4 = test(eta2, i2)
print(f"Mínimo de épocas necessárias: {min_epochs4}")
print(f"Média do total de ajustes: {mean4}")
print(f"Desvio padrão do total de ajustes: {std4}")

Mínimo de épocas necessárias: 14
Média do total de ajustes: 1311.6
Desvio padrão do total de ajustes: 848.7591177713498


In [127]:
# eta = 0.01 e intervalo [-0.5, 0.5]
min_epochs5, mean5, std5 = test(eta3, i1)
print(f"Mínimo de épocas necessárias: {min_epochs5}")
print(f"Média do total de ajustes: {mean5}")
print(f"Desvio padrão do total de ajustes: {std5}")

Mínimo de épocas necessárias: 2
Média do total de ajustes: 92.9
Desvio padrão do total de ajustes: 32.565165437933835


In [128]:
# eta = 0.01 e intervalo [-100, 100]
min_epochs6, mean6, std6 = test(eta3, i2)
print(f"Mínimo de épocas necessárias: {min_epochs6}")
print(f"Média do total de ajustes: {mean6}")
print(f"Desvio padrão do total de ajustes: {std6}")

Mínimo de épocas necessárias: 58
Média do total de ajustes: 12825.4
Desvio padrão do total de ajustes: 5150.801902616718


##### Tabela de resultados:

In [129]:
table = PrettyTable()

# table.set_style(TableStyle.MARKDOWN)
table.vertical_char = " "

table.field_names = ["Taxa de Aprendizado", "Intervalo de Pesos", "Quantidade de Ajustes", "Menor Número de Épocas para Convergência"]

table.add_row([eta1, i1, f"{mean1} += {std1:.1f}", min_epochs1])
table.add_row([eta1, i2, f"{mean2} += {std2:.1f}", min_epochs2])
table.add_row([eta2, i1, f"{mean3} += {std3:.1f}", min_epochs3])
table.add_row([eta2, i2, f"{mean4} += {std4:.1f}", min_epochs4])
table.add_row([eta3, i1, f"{mean5} += {std5:.1f}", min_epochs5])
table.add_row([eta3, i2, f"{mean6} += {std6:.1f}", min_epochs6])

print(table)

+---------------------+--------------------+-----------------------+------------------------------------------+
  Taxa de Aprendizado   Intervalo de Pesos   Quantidade de Ajustes   Menor Número de Épocas para Convergência  
+---------------------+--------------------+-----------------------+------------------------------------------+
          0.4              [-0.5, 0.5]            33.8 += 14.7                          2                      
          0.4              [-100, 100]           284.9 += 148.3                         9                      
          0.1              [-0.5, 0.5]            33.4 += 8.4                           9                      
          0.1              [-100, 100]          1311.6 += 848.8                         14                     
          0.01             [-0.5, 0.5]            92.9 += 32.6                          2                      
          0.01             [-100, 100]         12825.4 += 5150.8                        58              